pinnedLeanToolchain: leanprover/lean4:v4.30.0
proofLakefileUrl: .
paperTitle: Your Submission Paper
namespaceSlug: TestPaper
surfaceLakefilePath: surface-package/lakefile.lean
abstractUrl: abstract.tex
submissionIssueNumber: "1"
submissionIssueUrl: "https://github.com/clemenskuske/Lean-Meta-Library/issues/1"
surfaceEntries:
  - type: Definition
    name: TestPaper.Surface.Definition.ConnectedGraph
    folder: surface-package/ConnectedGraph
    usedSurfaceFiles: []
  - type: Theorem
    name: TestPaper.Surface.Theorem.ConnectedIffReachable
    folder: surface-package/ConnectedIffReachable
    usedSurfaceFiles: []
proofs:
  - theorem: TestPaper.Surface.Theorem.ConnectedIffReachable.connected_iff_reachable
    proofFile: proofs/ConnectedIffReachableProof.lean
bibtex: ""
paper:
  paperTitle: Your Submission Paper
  arxivUrl: ""
  onlineSource: ""
  doi: ""
  orcids: []
  journalOrConference: ""
  keywords: []
