#!/usr/bin/env node
// Generates ProofCheck.lean and asks Lean to verify each proof has exactly the corresponding surface theorem type.
import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  declarationNames,
  isConjectureProofEntry,
  loadContext,
  maxBuildOutputBytes,
  proofConstantForTheorem,
  proofModuleForFile,
  proofNamespaceForTheorem,
  readIfExists,
  report,
  surfaceModuleForEntry,
  surfaceNamespaceForEntry
} from "./common.mjs";

const { packageRoot, meta } = loadContext();
const errors = [];
const proofByTheorem = new Map(
  (meta.proofs ?? []).filter((proof) => !isConjectureProofEntry(proof)).map((proof) => [proof.theorem, proof])
);
const imports = new Set();
const examples = [];
const proofCheckPath = join(packageRoot, "ProofCheck.lean");

for (const entry of (meta.surfaceEntries ?? []).filter((item) => item.type === "Theorem")) {
  addTheoremChecks(entry);
}

try {
  writeFileSync(proofCheckPath, proofCheckSource(), "utf8");
} catch (error) {
  errors.push(`could not write ProofCheck.lean: ${error.message}`);
}

if (errors.length === 0 && examples.length > 0) {
  const result = spawnSync("lake", ["--dir", packageRoot, "lean", proofCheckPath], {
    encoding: "utf8",
    maxBuffer: maxBuildOutputBytes
  });

  if (result.error) {
    errors.push(`could not run Lean proof check: ${result.error.message}`);
  } else if (result.status !== 0) {
    errors.push(`ProofCheck.lean failed to build\n${result.stdout}${result.stderr}`.trim());
  }
}

report("proof check examples", errors);

function addTheoremChecks(entry) {
  const source = readIfExists(join(packageRoot, entry.folder ?? "", "Surface.lean"));
  if (!source) {
    return;
  }

  const namespace = surfaceNamespaceForEntry(entry);
  const declarations = [
    ...declarationNames(source, "axiom"),
    ...declarationNames(source, "theorem")
  ];
  if (declarations.length === 0) {
    errors.push(`${entry.folder}/Surface.lean has no surface theorem declaration to check`);
    return;
  }

  const surfaceModule = surfaceModuleForEntry(entry);
  if (surfaceModule) {
    imports.add(surfaceModule);
  }

  for (const declaration of declarations) {
    const surfaceName = `${namespace}.${declaration}`;
    const proof = proofByTheorem.get(surfaceName);
    if (!proof) {
      errors.push(`surface theorem has no matching proof metadata entry: ${surfaceName}`);
      continue;
    }

    const proofModule = proofModuleForFile(proof.proofFile);
    if (!proofModule || !isLeanModuleName(proofModule)) {
      errors.push(`could not infer proof module for ${proof.proofFile ?? "(missing proofFile)"}`);
      continue;
    }
    imports.add(proofModule);

    const proofNamespace = proofNamespaceForTheorem(surfaceName);
    if (!proofNamespace) {
      errors.push(`surface theorem is not in a Surface.Theorem namespace: ${surfaceName}`);
      continue;
    }

    const proofName = `${proofNamespace}.${proofConstantForTheorem(surfaceName)}`;
    examples.push(`example : ${surfaceName} := ${proofName}`);
  }
}

function proofCheckSource() {
  const importLines = [...imports]
    .filter(isLeanModuleName)
    .sort()
    .map((moduleName) => `import ${moduleName}`);
  const body = examples.length > 0 ? examples.join("\n") : "-- No surface theorem proofs to check.";

  return [
    "-- This file is generated by lml test. Do not edit by hand.",
    ...importLines,
    "",
    "private instance proofCheckCoeSort {P : Prop} : CoeSort P (Sort 0) where",
    "  coe _ := P",
    "",
    body,
    ""
  ].join("\n");
}

function isLeanModuleName(name) {
  return /^[A-Za-z_][A-Za-z0-9_']*(\.[A-Za-z_][A-Za-z0-9_']*)*$/.test(name);
}
