proofLakefilePath: lakefile.lean
statementLakefilePath: statements/lakefile.lean
abstractPath: abstract.tex
submissionTitle: Sorry Proof Fixture
statements:
  - Name: ConnectedGraph
    Type: Definition
    Statement:
      CurrentSubmission: true
      Name: SorryProof.Statements.ConnectedGraph.IsConnectedGraph
      LeanStatement: statements/SorryProof/Statements/ConnectedGraph.lean
      LatexDefinition: statements/SorryProof/Statements/ConnectedGraph.tex
    DeclarationReferences: []
  - Name: ConnectedIffReachable
    Type: Axiom
    Statement:
      CurrentSubmission: true
      Name: SorryProof.Statements.ConnectedIffReachable.connected_iff_reachable
      LeanStatement: statements/SorryProof/Statements/ConnectedIffReachable.lean
      LatexDefinition: statements/SorryProof/Statements/ConnectedIffReachable.tex
    DeclarationReferences: []
proofs:
  - Name: ConnectedIffReachableProof
    Type: proof
    Theorem:
      Name: SorryProof.Statements.ConnectedIffReachable.connected_iff_reachable
      LeanStatement: statements/SorryProof/Statements/ConnectedIffReachable.lean
      LatexDefinition: statements/SorryProof/Statements/ConnectedIffReachable.tex
      CurrentSubmission: true
    Proof:
      File: proofs/ConnectedIffReachableProof.lean
      Name: SorryProof.Proofs.Statement.ConnectedIffReachable.connected_iff_reachable
    DeclarationReferences: []
bibtex-entries: []
submissionSlug: sorry-proof
proofLeanToolchainPath: lean-toolchain
statementLeanToolchainPath: statements/lean-toolchain
